### PR TITLE
Isochrone

### PR DESCRIPTION
**Pull request by Chris-Kropp**

### CODE REVIEW

**Review by BridgerJones — CHANGES_REQUESTED** [review]
Everything looks good. Only one change before I would merge it. i notice that on line 23 in config.py the distance is changed from 50,000 to 250,000. The reason I had it at 50k was because if you try and load more nodes than that it takes a very long time and sometimes OSM throws an error or times out. If you could change it back to 50k that would be great. Other than that the isochrone with fastsim looks really good.

**Comment by Chris-Kropp** [comment]
I changed it to 250k because the fastsim isochrone was going off the edge of the map on anything under ~230k, I'll changed it back, should I leave a comment indicating the issue in config?

**Comment by BridgerJones** [comment]
Yeah just leave a note in there in the comments mentioning the issue. Perhaps there is a way to adjust the isochrone window size?

**Comment by Max-Clark** [comment]
Maybe it would make sense to do the battery power and battery percentage as arguments to the isochrone function? So we'd pass in 23 (kWh) and 0.25 to see the 25% range capabilities? I think that would be easy enough for a user to comprehend and be easy to implement.

**Comment by BridgerJones** [comment]
@Max-Clark We could try something like that in our next stable build. I changed this to merge to development as that has other pending changes to be merged to main. @Chris-Kropp if you made the changes to the config.py just push it to remote again and it should update this PR. After that I can get it merged and then work on getting  the next stable release on main.

**Review by BridgerJones — APPROVED** [review]

**Pull request merged**
